
services:
  h3prompt:
    build: .
    restart: always
    volumes:
#      - ./checkpoint-2470:/tmp/model
      - /data3/gate/cache/transformers/:/home/mambauser/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]
